import { mkdir, writeFile } from 'node:fs/promises';

import { launchCatalogFileSchema } from '@/domain/recipe-catalog';
import { ingredientCatalog, launchCatalogFile } from '../../data/recipes';

const parsed = launchCatalogFileSchema.parse(launchCatalogFile);
const generatedAt = parsed.generatedAt;
const sql = (value: string | number | null): string => {
  if (value === null) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${value.replaceAll("'", "''")}'`;
};
const json = (value: unknown) => sql(JSON.stringify(value));

const lines: string[] = [
  '-- Generated by scripts/recipes/generate-sql.ts. Do not edit manually.',
  'PRAGMA foreign_keys = ON;',
  'BEGIN TRANSACTION;',
];

for (const ingredient of ingredientCatalog) {
  lines.push(
    `INSERT OR IGNORE INTO ingredients (id, canonical_name_en, canonical_name_zh, category, default_unit, status, created_at, updated_at) VALUES (${sql(ingredient.id)}, ${sql(ingredient.nameEn)}, ${sql(ingredient.nameZh)}, ${sql(ingredient.category)}, ${sql(ingredient.defaultUnit)}, 'active', ${sql(generatedAt)}, ${sql(generatedAt)});`,
  );
  for (const allergen of ingredient.allergens ?? []) {
    lines.push(
      `INSERT OR IGNORE INTO ingredient_allergens (ingredient_id, allergen_id, presence, reviewed_at) SELECT ${sql(ingredient.id)}, id, ${sql(allergen.presence)}, ${allergen.presence === 'unknown' ? 'NULL' : sql(generatedAt)} FROM allergens WHERE code = ${sql(allergen.code)};`,
    );
  }
}

for (const recipe of parsed.recipes) {
  const recipeStatus = recipe.status === 'published' ? 'published' : 'review';
  lines.push(
    `INSERT OR REPLACE INTO recipes (id, slug, status, primary_role_id, base_servings, active_minutes, total_minutes, advance_minutes, difficulty, spice_level, hold_quality, reheating_quality, child_friendly, kitchen_test_status, scaling_notes_json, safety_notes, created_at, updated_at, published_at) SELECT ${sql(recipe.id)}, ${sql(recipe.slug)}, ${sql(recipeStatus)}, id, ${recipe.baseServings}, ${recipe.activeMinutes}, ${recipe.totalMinutes}, ${recipe.advanceMinutes}, ${sql(recipe.difficulty)}, ${recipe.spiceLevel}, ${recipe.holdQuality}, ${recipe.reheatingQuality}, ${recipe.childFriendly ? 1 : 0}, ${sql(recipe.kitchenTestStatus)}, ${json({ ...recipe.scalingNotes, substitutions: recipe.substitutions })}, ${sql(recipe.safetyNotes)}, ${sql(generatedAt)}, ${sql(generatedAt)}, ${recipeStatus === 'published' ? sql(generatedAt) : 'NULL'} FROM recipe_roles WHERE code = ${sql(recipe.primaryRole)};`,
  );

  for (const [locale, translation] of Object.entries(recipe.translations)) {
    lines.push(
      `INSERT OR REPLACE INTO recipe_translations (recipe_id, locale, title, summary, serving_note, instructions_json, ai_assisted) VALUES (${sql(recipe.id)}, ${sql(locale)}, ${sql(translation.title)}, ${sql(translation.summary)}, ${sql(translation.servingNote)}, ${json(translation.instructions)}, ${translation.aiAssisted ? 1 : 0});`,
    );
  }

  for (const [sequence, ingredient] of recipe.ingredients.entries()) {
    lines.push(
      `INSERT OR REPLACE INTO recipe_ingredients (id, recipe_id, ingredient_id, sequence, normalized_quantity, normalized_unit, display_quantity, preparation_note_en, preparation_note_zh, optional, scaling_strategy, substitution_group) VALUES (${sql(`${recipe.id}_ing_${sequence + 1}`)}, ${sql(recipe.id)}, ${sql(ingredient.ingredientId)}, ${sequence + 1}, ${ingredient.quantity === null ? 'NULL' : ingredient.quantity}, ${sql(ingredient.unit)}, ${sql(ingredient.displayQuantity)}, ${sql(ingredient.preparationNoteEn)}, ${sql(ingredient.preparationNoteZh)}, ${ingredient.optional ? 1 : 0}, ${sql(ingredient.scalingStrategy)}, ${sql(ingredient.substitutionGroup)});`,
    );
  }

  for (const role of [recipe.primaryRole, ...recipe.secondaryRoles]) {
    lines.push(
      `INSERT OR IGNORE INTO recipe_roles_map (recipe_id, role_id, suitability_score) SELECT ${sql(recipe.id)}, id, 100 FROM recipe_roles WHERE code = ${sql(role)};`,
    );
  }
  for (const cuisine of recipe.cuisines) {
    lines.push(
      `INSERT OR IGNORE INTO recipe_cuisines (recipe_id, cuisine_id, weight) SELECT ${sql(recipe.id)}, id, 100 FROM cuisines WHERE code = ${sql(cuisine)};`,
    );
  }
  for (const method of recipe.methods) {
    lines.push(
      `INSERT OR IGNORE INTO recipe_methods (recipe_id, method_id, is_primary) SELECT ${sql(recipe.id)}, id, 1 FROM cooking_methods WHERE code = ${sql(method)};`,
    );
  }
  for (const equipment of recipe.equipment) {
    lines.push(
      `INSERT OR REPLACE INTO recipe_equipment (recipe_id, equipment_id, quantity, occupied_minutes, required) SELECT ${sql(recipe.id)}, id, ${equipment.quantity}, ${equipment.occupiedMinutes}, ${equipment.required ? 1 : 0} FROM equipment WHERE code = ${sql(equipment.id)};`,
    );
  }
  for (const [style, score] of Object.entries(recipe.servingStyles)) {
    lines.push(
      `INSERT OR REPLACE INTO recipe_serving_styles (recipe_id, serving_style, suitability_score) VALUES (${sql(recipe.id)}, ${sql(style)}, ${score});`,
    );
  }
  for (const dietTag of recipe.dietTags) {
    lines.push(
      `INSERT OR REPLACE INTO recipe_diet_tags (recipe_id, diet_tag_id, verification) SELECT ${sql(recipe.id)}, id, ${sql(dietTag.verification)} FROM diet_tags WHERE code = ${sql(dietTag.code)};`,
    );
  }
  for (const allergen of recipe.allergens) {
    lines.push(
      `INSERT OR REPLACE INTO ingredient_allergens (ingredient_id, allergen_id, presence, reviewed_at) SELECT ${sql(allergen.ingredientId)}, id, ${sql(allergen.presence)}, ${allergen.reviewed ? sql(generatedAt) : 'NULL'} FROM allergens WHERE code = ${sql(allergen.allergenCode)};`,
    );
  }

  lines.push(
    `INSERT OR REPLACE INTO recipe_nutrition_snapshots (id, recipe_id, source_name, source_version, per_serving_energy_kj, per_serving_energy_kcal, protein_g, fat_g, saturated_fat_g, carbohydrate_g, sugars_g, fibre_g, sodium_mg, confidence, calculated_at, reviewed_at) VALUES (${sql(`${recipe.id}_nutrition_1`)}, ${sql(recipe.id)}, ${sql(recipe.nutrition.sourceName)}, ${sql(recipe.nutrition.sourceVersion)}, ${recipe.nutrition.energyKj}, ${recipe.nutrition.energyKcal}, ${recipe.nutrition.proteinG}, ${recipe.nutrition.fatG}, ${recipe.nutrition.saturatedFatG}, ${recipe.nutrition.carbohydrateG}, ${recipe.nutrition.sugarsG}, ${recipe.nutrition.fibreG}, ${recipe.nutrition.sodiumMg}, ${recipe.nutrition.confidence}, ${sql(generatedAt)}, NULL);`,
  );
  lines.push(
    `INSERT OR REPLACE INTO recipe_cost_snapshots (id, recipe_id, region_code, currency, total_cents, per_serving_cents, pantry_policy, price_version, calculated_at) VALUES (${sql(`${recipe.id}_cost_1`)}, ${sql(recipe.id)}, ${sql(recipe.cost.regionCode)}, 'AUD', ${recipe.cost.totalCents}, ${recipe.cost.perServingCents}, ${sql(recipe.cost.pantryPolicy)}, ${sql(recipe.cost.priceVersion)}, ${sql(generatedAt)});`,
  );
  lines.push(
    `INSERT OR REPLACE INTO media_assets (id, object_key, media_type, subject_type, mime_type, width, height, alt_en, alt_zh, source_url, license_code, attribution, ai_model, ai_prompt, generated_at, rights_reviewed_at, created_at) VALUES (${sql(`${recipe.id}_media_1`)}, ${sql(recipe.media.objectKey)}, ${sql(recipe.media.mediaType)}, 'recipe', ${sql(recipe.media.mimeType)}, ${recipe.media.width}, ${recipe.media.height}, ${sql(recipe.media.altEn)}, ${sql(recipe.media.altZh)}, ${sql(recipe.media.sourceUrl)}, ${sql(recipe.media.licenseCode)}, ${sql(recipe.media.attribution)}, ${sql(recipe.media.aiModel)}, ${sql(recipe.media.aiPrompt)}, ${sql(recipe.media.generatedAt)}, ${sql(recipe.media.rightsReviewedAt)}, ${sql(generatedAt)});`,
  );
  lines.push(
    `INSERT OR REPLACE INTO recipe_media (recipe_id, media_id, display_order, is_primary) VALUES (${sql(recipe.id)}, ${sql(`${recipe.id}_media_1`)}, 0, 1);`,
  );
  lines.push(
    `INSERT OR REPLACE INTO content_sources (id, source_type, provider_name, source_url, license_code, attribution_required, caching_allowed, terms_checked_at, retrieved_at) VALUES (${sql(`${recipe.id}_source_1`)}, ${sql(recipe.source.sourceType)}, ${sql(recipe.source.providerName)}, ${sql(recipe.source.sourceUrl)}, ${sql(recipe.source.licenseCode)}, ${recipe.source.attributionRequired ? 1 : 0}, ${recipe.source.cachingAllowed ? 1 : 0}, ${sql(generatedAt)}, ${sql(generatedAt)});`,
  );
  lines.push(
    `INSERT OR REPLACE INTO recipe_sources (recipe_id, source_id, relationship) VALUES (${sql(recipe.id)}, ${sql(`${recipe.id}_source_1`)}, 'original');`,
  );
  lines.push(
    `INSERT OR REPLACE INTO recipe_versions (id, recipe_id, version_number, snapshot_json, change_summary, created_at) VALUES (${sql(`${recipe.id}_version_1`)}, ${sql(recipe.id)}, 1, ${json(recipe)}, 'Launch catalogue import', ${sql(generatedAt)});`,
  );
}

const recipeIdsSql = parsed.recipes.map((recipe) => sql(recipe.id)).join(', ');
lines.push(`DELETE FROM recipe_search_fts WHERE recipe_id IN (${recipeIdsSql});`);
lines.push(
  `INSERT INTO recipe_search_fts (recipe_id, locale, title, summary, ingredient_terms, cuisine_terms) SELECT r.id, t.locale, t.title, t.summary, COALESCE((SELECT GROUP_CONCAT(i.canonical_name_en || ' ' || i.canonical_name_zh, ' ') FROM recipe_ingredients ri JOIN ingredients i ON i.id = ri.ingredient_id WHERE ri.recipe_id = r.id), ''), COALESCE((SELECT GROUP_CONCAT(c.name_en || ' ' || c.name_zh, ' ') FROM recipe_cuisines rc JOIN cuisines c ON c.id = rc.cuisine_id WHERE rc.recipe_id = r.id), '') FROM recipes r JOIN recipe_translations t ON t.recipe_id = r.id WHERE r.status = 'published' AND r.id IN (${recipeIdsSql});`,
);
lines.push('COMMIT;');

await mkdir('.generated', { recursive: true });
await writeFile('.generated/launch-recipes.sql', `${lines.join('\n')}\n`, 'utf8');
console.log(`Generated .generated/launch-recipes.sql with ${parsed.recipes.length} recipes.`);
